### ISSUE TITLE
Controllare se evento è esistente e controllare data

### ISSUE THREAD

**Issue by SamueleCappelletti** [FraMichi/ProgettoTrentinoEventi#11]
@TLZ2000 nel file "eventSubscription", dove crei l'iscrizione ad un evento, non controlli se l'evento esiste o meno

**Comment by SamueleCappelletti** [comment]
sempre nello stesso file, quando controlli se un utente può essere iscritto ad un evento, non controlli se l'utente e l'evento esistono, e poi non controlli la data dell'evento. Così ci si potrebbe iscrivere anche ad eventi passati

**Comment by SamueleCappelletti** [comment]
E poi mancano ancora altri controlli sempre di questo tipo

**Comment by TLZ2000** [comment]
Le date sono corrette
Manca il controllo se l'evento esiste (roba per testing)

**Comment by TLZ2000** [comment]
Corretto
